[package]
name = "custom-http-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httpdate = "1.0.2"
ctrlc = { version = "3.0", features = ["termination"] }
